services:
  # 1. Naming Server (Eureka) - Start this first
  naming-server:
    image: onkar22/mmv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 800m
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  # 2. API Gateway
  api-gateway:
    image: onkar22/mmv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 512m
    ports:
      - "8765:8765"
    networks:
      - microservice-network
    depends_on:
      - naming-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans

  # 3. Currency Exchange Service
  currency-exchange:
    image: onkar22/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 800m
    ports:
      - "8000:8000"
    networks:
      - microservice-network
    depends_on:
      - naming-server
      - currency-db
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka/
      # If you use H2 Console, it will be available at localhost:8000/h2-console
      EXCHANGE_API_KEY: ${MY_SECRET_API_KEY}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
  # 4. Currency Conversion Service
  currency-conversion:
    image: onkar22/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 800m
    ports:
      - "8100:8100"
    networks:
      - microservice-network
    depends_on:
      - naming-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans

  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    mem_limit: 512m
    ports:
      - "9411:9411"
    networks:
      - microservice-network
    # 5. PostgreSQL Database
  currency-db:
      image: postgres:15-alpine
      mem_limit: 512m
      environment:
        POSTGRES_DB: currencydb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      networks:
        - microservice-network
      volumes:
        - pgdata:/var/lib/postgresql/data

networks:
  microservice-network:
    driver: bridge
  # Add this at the very bottom under 'networks'
volumes:
  pgdata:
